// AUTO-GENERATED FILE. Do not edit by hand.
// Generated by frontend/scripts/generate-changelog.mjs from git tags and
// frontend/src/data/changelog.manual.json. Re-run `pnpm run build` (or the
// generator directly) to refresh.

export interface ChangelogEntry {
  version: string
  date: string
  highlights: string[]
}

export const CHANGELOG: ChangelogEntry[] = [
  {
    "version": "Unreleased",
    "date": "",
    "highlights": [
      "Configurable per-user enrichment-cache TTL.",
      "Text-size control for the Settings window.",
      "Brand-mark config + shared <Brand> component.",
      "Dispose portal-loop engines in sync TestClient tests.",
      "Re-open flaky CI hang (recurred despite PR #77).",
      "Owner-surface theme + ephemeral login toggle.",
      "Dispose async engines in teardown to end flaky CI hang.",
      "Single-job release resolving the target from the tag.",
      "Capture flaky CI pre-commit (3.12) hang.",
      "Configurable brand-logo knobs + fill the header lockup.",
      "Dogfood the Docker stack at the end of each change.",
      "Security hardening: tighten CSP + uniform file-or-env config sourcing.",
      "Declare the subdir tagging method.",
      "Move the Spotify-audit watch list to docs.",
      "3-level theme system with dark + light.",
      "Opt in to the merge-finalization hook.",
      "Prune completed items merged in #63–#66.",
      "Attribute Spotify in the UI + document retention posture.",
      "Spotify audit: Premium gating message + saved-tracks read decision.",
      "Centralise upstream Spotify 401 → clean 401 across the API.",
      "Track Info panel overhaul + per-component versioning scheme.",
      "Day-glo console rollout: Settings, UserMenu, RecipeBuilder + fixes.",
      "Prune backlog, record SQLite-only decision (ADR-0003).",
      "Bump the backend group across 1 directory with 4 updates.",
      "Bump the frontend group across 1 directory with 4 updates.",
      "…and 166 earlier changes."
    ]
  },
  {
    "version": "0.4.0",
    "date": "2026-04-10",
    "highlights": [
      "New About tab in Settings shows version numbers, the GitHub link and public data sources.",
      "Last.fm queue panel lets you select, retry or delete pending scrobbles individually.",
      "Track trivia (Last.fm, MusicBrainz, Wikipedia) is now cached for up to a week with a manual clear button."
    ]
  },
  {
    "version": "0.3.0",
    "date": "2026-03-12",
    "highlights": [
      "Favorites sync between Spotify and Last.fm with conflict resolution.",
      "Background sync interval is configurable per account.",
      "Custom display name option in the Connections tab."
    ]
  },
  {
    "version": "0.2.0",
    "date": "2026-02-04",
    "highlights": [
      "Playlist recipes with sort key chaining and live previews.",
      "Recently used playlists panel for one-click access.",
      "Track detail panel with cross-provider trivia."
    ]
  },
  {
    "version": "0.1.0",
    "date": "2026-01-15",
    "highlights": [
      "Initial Pigify release with Spotify login and basic playlist browsing."
    ]
  }
]
