// AUTO-GENERATED FILE. Do not edit by hand.
// Generated by frontend/scripts/generate-changelog.mjs from git tags and
// frontend/src/data/changelog.manual.json. Re-run `pnpm run build` (or the
// generator directly) to refresh.

export interface ChangelogEntry {
  version: string
  date: string
  highlights: string[]
}

export const CHANGELOG: ChangelogEntry[] = [
  {
    "version": "Unreleased",
    "date": "",
    "highlights": [
      "Make the access gate on-by-default and fail-closed.",
      "Refresh generated changelog before PR.",
      "Built-in access gate (Spotify-ID allowlist).",
      "Built-in auth, phase 1: session seam + dev login bypass.",
      "Document changelog regen as a pre-PR prep step.",
      "Extract pure component helpers into tested modules.",
      "Cover the large components (RecipeBuilder, Settings, NowPlaying).",
      "Wire markdownlint into pre-commit + fix docs.",
      "Re-enable useExhaustiveDependencies; fix re-fetch loop.",
      "Re-enable biome noExplicitAny + noArrayIndexKey.",
      "Guard spotify.py None payloads; remove pyright pragma.",
      "Add secret-detection hooks; refresh QA-doc statuses.",
      "Add jsdom + RTL component tests.",
      "Clean up TODO.md.",
      "Skip no-commit-to-branch hook in CI (fixes red master push runs).",
      "Matrix Pre-commit on Python; drop redundant Backend tests job.",
      "Make deployment generic and auth-agnostic.",
      "Make DAST a blocking gate (allowlist deliberate warns, skip docs-only).",
      "Make Semgrep a blocking gate (triage findings, skip docs-only).",
      "Add TODO for jsdom component render testing.",
      "Upgrade to React 19.",
      "Upgrade backend image to Python 3.14 + add test matrix.",
      "Upgrade to Vite 8 + Vitest 4.",
      "Bump @types/node from 22.19.20 to 25.9.2 in /frontend.",
      "Bump node from 20-alpine to 26-alpine in /frontend.",
      "…and 120 earlier changes."
    ]
  },
  {
    "version": "0.4.0",
    "date": "2026-04-10",
    "highlights": [
      "New About tab in Settings shows version numbers, the GitHub link and public data sources.",
      "Last.fm queue panel lets you select, retry or delete pending scrobbles individually.",
      "Track trivia (Last.fm, MusicBrainz, Wikipedia) is now cached for up to a week with a manual clear button."
    ]
  },
  {
    "version": "0.3.0",
    "date": "2026-03-12",
    "highlights": [
      "Favorites sync between Spotify and Last.fm with conflict resolution.",
      "Background sync interval is configurable per account.",
      "Custom display name option in the Connections tab."
    ]
  },
  {
    "version": "0.2.0",
    "date": "2026-02-04",
    "highlights": [
      "Playlist recipes with sort key chaining and live previews.",
      "Recently used playlists panel for one-click access.",
      "Track detail panel with cross-provider trivia."
    ]
  },
  {
    "version": "0.1.0",
    "date": "2026-01-15",
    "highlights": [
      "Initial Pigify release with Spotify login and basic playlist browsing."
    ]
  }
]
