// AUTO-GENERATED FILE. Do not edit by hand.
// Generated by frontend/scripts/generate-changelog.mjs from git tags and
// frontend/src/data/changelog.manual.json. Re-run `pnpm run build` (or the
// generator directly) to refresh.

export interface ChangelogEntry {
  version: string
  date: string
  highlights: string[]
}

export const CHANGELOG: ChangelogEntry[] = [
  {
    "version": "Unreleased",
    "date": "",
    "highlights": [
      "Share-to-social popover.",
      "Own secrets win even with coattails permission.",
      "Grokipedia free-search link.",
      "Wrap the Songfacts contact item at 78 cols.",
      "Wikipedia resolution fallbacks + album/band links.",
      "Songfacts block with song + artist search links.",
      "Notify when playback isn't on pigify.",
      "\"Search <provider>\" link when a provider has no result.",
      "A−/A+ text-size control on the panel.",
      "Add a MusicBrainz section (rule + skill + alignment).",
      "Wrap the duration-icon item at 78 cols.",
      "Wrap versioning + duration-icon items at 78 cols.",
      "Versioning (do last) + custom duration-icon backlog.",
      "Load each provider section independently, with spinners.",
      "Per-row info icon to open the Track Info panel.",
      "Drop the bottom-right resize grip mark.",
      "Resize the floating panel from any edge or corner.",
      "Track Info — edge/corner resize + Grokipedia provider.",
      "Make the Track Info panel a floating window.",
      "Day-glo console rollout: Settings, UserMenu, RecipeBuilder + fixes.",
      "Track Info floating panel + unify the two Sort by UIs.",
      "Wrap the filter/sort intro at 78 cols.",
      "Add filter/sort control items to Smart Filters.",
      "Align the Sort by / Take / Source row controls.",
      "Expand Smart Filters backlog (builder CRUD, sources, lifecycle).",
      "…and 244 earlier changes."
    ]
  },
  {
    "version": "0.4.0",
    "date": "2026-04-10",
    "highlights": [
      "New About tab in Settings shows version numbers, the GitHub link and public data sources.",
      "Last.fm queue panel lets you select, retry or delete pending scrobbles individually.",
      "Track trivia (Last.fm, MusicBrainz, Wikipedia) is now cached for up to a week with a manual clear button."
    ]
  },
  {
    "version": "0.3.0",
    "date": "2026-03-12",
    "highlights": [
      "Favorites sync between Spotify and Last.fm with conflict resolution.",
      "Background sync interval is configurable per account.",
      "Custom display name option in the Connections tab."
    ]
  },
  {
    "version": "0.2.0",
    "date": "2026-02-04",
    "highlights": [
      "Playlist recipes with sort key chaining and live previews.",
      "Recently used playlists panel for one-click access.",
      "Track detail panel with cross-provider trivia."
    ]
  },
  {
    "version": "0.1.0",
    "date": "2026-01-15",
    "highlights": [
      "Initial Pigify release with Spotify login and basic playlist browsing."
    ]
  }
]
